# permissions for end users to edit memcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memcached-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project-v4-with-deploy-image
    app.kubernetes.io/part-of: project-v4-with-deploy-image
    app.kubernetes.io/managed-by: kustomize
  name: memcached-editor-role
rules:
- apiGroups:
  - example.com.testproject.org
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.testproject.org
  resources:
  - memcacheds/status
  verbs:
  - get
